#!/usr/bin/env bash

DIR="$(dirname "$(cd $(dirname $0); pwd)")"
PACKAGES=( "core" "cli" )

for i in ${PACKAGES[@]}; do
  cp $DIR/LICENSE $i
  cp $DIR/README.md $i
  cp -r $DIR/assets $i

  cd $DIR/$i
  npm run build
  npm version $1
  npm publish
done
